config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

# allows up to avoid the signup route error
  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name,  :validate => true
  attributes :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message, :validate => true
  attributes :nickname,   :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "jenkins.webdesigns@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable allows others to signup
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = "Cannot send message."
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :find_post, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, except: [:index, :show]
 def index
   @posts = Post.all.paginate(page: params[:page], per_page: 5).order('created_at DESC')
 end

 def new
   @post = Post.new
 end

 def create
   @post = Post.new post_params

   if @post.save
     redirect_to @post, notice: "Saved Successfully"
   else
     render 'new', notice: "Unable to save."
   end
 end

def show
end

def edit
end

def update
  if @post.update post_params
    redirect_to @post, notice: "Saved Successfully"
  else
    render 'edit'
  end
end

def destroy
  @post.destroy
  redirect_to posts_path
end

private
  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_action :find_project, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Saved Successfully"
    else
      render 'new', notice: "Unable to save."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
     redirect_to @project, notice: "Saved Successfully"
    else
     render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
   params.require(:project).permit(:title, :description, :link, :slug)
  end

  def find_project
   @project  = Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, layer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    render_options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, render_options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="pg_title">Let's Make  <em>Something Great</em>  Together!</h1>
<div class="sm_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="pg_title">Let's Make  <em>Something Great</em>  Together!</h1>
<div class="sm_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>

  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %> <br> <br>

  <%= f.label :email, "Email Here" %> <br>
  <%= f.email_field :email, required: true %> <br> <br>

  <%= f.label :message %> <br>
  <%= f.text_area :message, as: :text %> <br> <br>

  <div class="hidden">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>
  </div>

  <%= f.submit 'Send Message', class: "button" %>

  <% end %>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127524947-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('require', 'linkid');
    gtag('config', 'UA-127524947-1');
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-9403158535239747",
      enable_page_level_ads: true
    });
  </script>
    <title> Yakeshia Jenkins </title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google-site-verification" content="4jXOcCCA0ARpKIDJd4yyyanRD0Wkb-HDCkP4h1m74yQ" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header id="main_nav" class="clearfix">
    <%= link_to "Yakeshia Jenkins", root_path, class: 'name' %>
    <nav>
      <%= link_to "Articles", posts_path %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "Contact", new_contact_path %>
      <% if user_signed_in? %>
       <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </nav>
  </header>

  <% if notice %>
  <p class="notice"><%= notice %></p>
  <% elsif alert %>
  <p class="alert"><%= alert %></p>
  <% end %>

    <%= yield %>

    <footer id="main_footer">
        <p class="copyright"> &copy; 2018 Yakeshia Jenkins &amp; Designed by <a href="http://mackenziechild.me" target="_blank">Mackenzie Child</a></p>
        <nav>
          <a href="https://twitter.com/yakeshiajenkins" target="_blank"><i class="fab fa-twitter"></i></a>
          <a href="https://github.com/yakeshiaj" target="_blank"><i class="fab fa-github"></i></a>
          <a href="https://bitbucket.org/yakeshiaj" target="_blank"><i class="fab fa-bitbucket"></i></a>
          <a href="https://www.facebook.com/YaYaFoeShoo" target="_blank"><i class="fab fa-facebook"></i></a>
        </nav>
    </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">

/* * *  RECOMMENDED CONFIGURATION VARIABLES: EDIT * * */

var disqus_config = function () {
this.page.title = '<%= @post.title %>';
this.page.url = '<%= url_for(action: 'show', controller: 'posts', only_path: false, protocol: 'https') %>' ;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
// DON'T EDIT BELOW THIS LINE
(function() {
var d = document, s = d.createElement('script');
s.src = 'https://devby-yj.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
   <h2> <%= pluralize(@post.errors.count, "error") %> Prevented this post from saving: </h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.label :title %> <br>
<%= f.text_field :title %> <br> <br>

<%= f.label :content, "Write your article here" %> <br>
<%= f.text_area :content %> <br> <br>

<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="sm_wrapper wrapper_padding">
  <h1 id="pg_title">Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="pg_title">Stuff I've Written</h1>

 <div id="posts_wrapper" class="sm_wrapper">
   <% @posts.each do |post| %>
     <div class="post">
     <p class="date"><%= post.created_at.strftime("%A, %b %d, %Y")%></p>
     <h2><%= link_to post.title, post %></h2>
      <hr class="post_hr">
    </div>
   <% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="sm_wrapper wrapper_padding">
  <h1 id="pg_title">New Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="sm_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @post.created_at.strftime("%A, %b %d, %Y")%></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @post.content %>
  </div>
   <% if user_signed_in? %>
   <div id="admin_links">
     <%= link_to "Edit Article", edit_post_path(@post) %>
     <%= link_to "Delete Article", post_path(@post), method: :delete, data: {confirm: "Click Ok to delete."} %>
   </div>
   <% end %>
  <hr>
  <div id="share_buttons">
    <p>Feel Free to Share </p>
    <a href="https://twitter.com/share?text=<%=@post.title%> by @yakeshiajenkins - &amp; url=<%= url_for([@post, {only_path: false}]) %>' " target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>' " target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>' " target="_blank"><i class="fab fa-google-plus"></i></a>
  </div>
  <hr>
  <%= render 'disqus' %>
  </div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
   <h2> <%= pluralize(@project.errors.count, "error") %> Prevented this project from saving: </h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.label :title %> <br>
<%= f.text_field :title %> <br> <br>

<%= f.label :description, "Write your project here" %> <br>
<%= f.text_area :description %> <br> <br>

<%= f.label :link %> <br>
<%= f.text_field :link %> <br> <br>

<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<div class="sm_wrapper wrapper_padding">
  <h1 id="pg_title">Edit Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="pg_title">Stuff I've Built</h1>

 <div id="posts_wrapper" class="sm_wrapper">
   <% @projects.each do |project| %>
     <div class="post">
     <p class="date"><%= project.created_at.strftime("%A, %b %d, %Y")%></p>
     <h2><%= link_to project.title, project %></h2>
      <hr class="post_hr">
    </div>
   <% end %>
</div>

app/views/projects/new.html.erb
<div class="sm_wrapper wrapper_padding">
  <h1 id="pg_title">New Project</h1>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="sm_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime("%A, %b %d, %Y")%></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @project.description %>
    <div class="btn_wrapper">
      <a href="<%= @project.link %>" class="project_btn" target="_blank">Learn More</a>
    </div>
  </div>

  <% if user_signed_in? %>
  <div id="admin_links">
    <%= link_to "Edit", edit_project_path(@project) %>
    <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Click Ok to delete."} %>
  </div>
  <% end %>
  <hr>
</div>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
    <div class="col-1 about home_content">
      <h2>About</h2>
      <hr>
      <p>I'm a developer living in Fayetteville, Arkansas. I attend the University of Arkansas; currently majoring in Computer Science.</p>
      <p>I work as a front-end dev at <a href="https://arkansas-water-center.uark.edu/" target="_blank">Arkansas Water Resources Center</a> . Also, I work as a
        PowerApps guru at the University of Arkansas, Information Technology Services department.
        On my spare time, I am learning how to design and code rails, nodejs, and other applications. </p>
      <p> You can find me being goofy on Youtube, sharing some code on Github, and building electronic kits.</p>
     <div class="btn_wrapper">
        <a href="https://drive.google.com/open?id=1mzGQRL74fdcF4ToaYTAwrXkKxtYNyjBO" target="_blank" class="button" >Resume</a>
    </div>
    </div>
    <div class="col-2 hyper home_content">
      <h2>Stuff I've Written</h2>
      <hr>
      <% @posts.each do |post| %>
        <h3><%= link_to post.title, post %></h3>
        <p class="date"><%= post.created_at.strftime("%A, %b %d, %Y")%></p>
      <% end %>
    </div>
    <div class="col-3 hyper home_content">
      <h2>Stuff I've Built</h2>
      <hr>
      <% @projects.each do |project| %>
        <h3><%= link_to project.title, project %></h3>
        <p class="date"><%= project.created_at.strftime("%A, %b %d, %Y")%></p>
      <% end %>
     </div>
  </div>